### ISSUE TITLE
CRONOS not supported ?

### ISSUE THREAD

**Issue by pfstudio53** [buildship-dev/webflow-nft-components#1]
Hi,

I try to setup a project on CRONOS testnet (338), is it possible?

I have this error :
Uncaught (in promise) Error: You must provide the json interface of the contract when instantiating a contract object.

Thank you

**Comment by theshadowagent** [comment]
Hi,

For CRONOS you should insert your contract ABI like this:
```html
<script src="https://cdn.jsdelivr.net/npm/web3@latest/dist/web3.min.js"></script>
<script type="text/javascript" src="https://unpkg.com/web3modal"></script>
<script type="text/javascript" src="https://unpkg.com/@walletconnect/web3-provider"></script>
<script>
    CONTRACT_ADDRESS = "<your CRONOS contract address here>"
    CONTRACT_ABI = "<your CRONOS contract ABI here>"
    NETWORK_ID = 338
</script>
<script crossorigin src="https://unpkg.com/react@17/umd/react.production.min.js"></script>
<script crossorigin src="https://unpkg.com/react-dom@17/umd/react-dom.production.min.js"></script>
<script crossorigin src="https://unpkg.com/@mui/material@5.1.0/umd/material-ui.production.min.js"></script>
<script type="module" src="https://buildship-dev.github.io/webflow-nft-components/mint/index.js"></script>
```
 
Usually, we use our API to auto-fetch contract ABIs for the most popular networks, but that's not working for CRONOS

**Comment by theshadowagent** [comment]
Just curious: are there any NFT projects live on CRONOS network?

**Comment by pfstudio53** [comment]
Thank you for your awnser. Yes there are live projects on Cronos since few weeks.

**Comment by pfstudio53** [comment]
Can I use your tool with customs contracts ? 

Because I always have "Minting error: TypeError: NFTContract.methods.getPrice is not a function. Please try again or contact us", so I imagine I have to custom your tool or change my contract

**Comment by caffeinum** [comment]
@pfstudio53 easiest way for you would be to add extra view function to your contract, something like:

```solidity
    function getPrice() public view returns (uint256) {
        return _price; // or whatever it's called for you
    }
```

**Comment by theshadowagent** [comment]
Closing this, feel free to reopen if you need more help :)

**Comment by caffeinum** [comment]
We added Cronos to list of networks
