### ISSUE TITLE
Access to fetch blocked by CORS

### ISSUE THREAD

**Issue by rainbowhat** [buildship-dev/webflow-nft-components#19]
N.A

**Comment by caffeinum** [comment]
Usually CORS error only indicate underlying error with the execution. Most probably it happens when the contract address is not verified or is one of non-supported networks.

In that case, you need to pass `CONTRACT_ABI` directly or `DEFAULTS.abiCacheURL` a URL from where to fetch ABI.

**Comment by caffeinum** [comment]
See here for details on how to do that: https://github.com/buildship-dev/webflow-nft-components/issues/22

**Comment by theshadowagent** [comment]
Please provide a screenshot of your error in Chrome Dev console
