### ISSUE TITLE
Mobile minting on Polygon doesn't work very well

### ISSUE THREAD

**Issue by thekesslereffect** [buildship-dev/webflow-nft-components#28]
Multiple users are saying that they try to mint with metamask but they cant get past the Polygon button. They tap it and nothing happens.

**Comment by thekesslereffect** [comment]
https://user-images.githubusercontent.com/24286691/156852637-e9c2fe8c-6c02-41e6-8671-1ea1a5c8f170.mp4

Here is a video of the issue

**Comment by theshadowagent** [comment]
Fixed as we removed the payment options modal
