### ISSUE TITLE
total-counter-error

### ISSUE THREAD

**Issue by moofawsaw** [buildship-dev/webflow-nft-components#5]
While using the testnet & example address; adding `#total-quantity` to a `<span>` returns `function () { [native code] } `

`   CONTRACT_ADDRESS = "0x8Fac2e25DFF0B248A19A66Ae8D530613c8Ff670B"
   IS_TESTNET = true`

**Comment by theshadowagent** [comment]
Fixed in #24a58907f14cb6deffc14a707215d07b80f86f34 (PR #6)
