### ISSUE TITLE
Error "Buildship widget doesn't know how to fetch price from your contract."(has been resolved)

### ISSUE THREAD

**Issue by Undoqaq** [buildship-dev/webflow-nft-components#55]
When I mint I get the error, please help me thanks.(has been resolved)

**Comment by Undoqaq** [comment]
It has been solved, the reason is that there is no my contract price name in web3.js, just add it and it will work.
`            const methodNameVariants = ['price', 'cost', 'public_sale_price', 'getPrice']`

**Comment by Ncrypt16** [comment]
Hi, how did you get the newly deployed vercel to work? It shows error 404 for me
