### ISSUE TITLE
Error in Vercel deployed page

### ISSUE THREAD

**Issue by Ncrypt16** [buildship-dev/webflow-nft-components#58]
Hi there! I'm trying to update web3.js but my PR is showing me 404 error on vercel. Thanks

**Comment by theshadowagent** [comment]
Hey! As I currently see, your Vercel deployment is live at https://nftcomponents-6gpiv59hr-buildship.vercel.app/. Unfortunately we can't provide any further Vercel hosting support for your PRs, so I'm closing this.
