### ISSUE TITLE
Rinkeby Test Network

### ISSUE THREAD

**Issue by zergaocean** [buildship-dev/webflow-nft-components#7]
Hi,

first of all, thank you for the great repo. 

wanted to ask if everything works on the Rinkeby network (ID 4)? Or if I'm doing something wrong... 

On the main network everything works fine. 

Best

**Comment by theshadowagent** [comment]
It surely works on the Rinkeby network, even in the example for testing. Can you share your embed code and website URL so I can figure out what's wrong?

**Comment by zergaocean** [comment]
Hi, 

Thanks for your answer. 

I got it. It worked after I verified the contract on etherscan.

**Comment by theshadowagent** [comment]
Thanks, I fixed the README to warn users about that.
