### ISSUE TITLE
can't mint

### ISSUE THREAD

**Issue by MineHenry0001** [buildship-dev/webflow-nft-components#71]
I have a mint code of my own in Eth test

<script>
   CONTRACT_ADDRESS = "0x60CAA9F8F4Bb499BAa138a51012A7BeD45dD8b29"
   NETWORK_ID = 4
   // place to put CONTRACT_ABI = [{...}]
</script>
<script src="https://cdn.nft-generator.art/js-sdk/v1.4.0/nft-art-generator-sdk/nft-art-generator-sdk.esm.js%22%3E"></script>
<link href="https://cdn.nft-generator.art/js-sdk/v1.4.0/nft-art-generator-sdk/nft-art-generator-sdk.js%22%3E" rel="stylesheet">

but still show error404

I try use the buildship test can to mint

**Comment by theshadowagent** [comment]
What is `https://cdn.nft-generator.art/js-sdk/v1.4.0/nft-art-generator-sdk/nft-art-generator-sdk.esm.js`? This is not related to Buildship, so closing this
