### ISSUE TITLE
Mint Button View

### ISSUE THREAD

**Issue by zergaocean** [buildship-dev/webflow-nft-components#8]
Every time I press the Mint button, this text appears on the button. 

Is there a way not to display it? It doesn't look so good aesthetically. 

Thanks in advance.

<img width="640" alt="screen-github" src="https://user-images.githubusercontent.com/97199109/148942240-d92a319b-f9e2-4e6d-b260-78ffc4787fbb.png">

**Comment by theshadowagent** [comment]
It should not be like that. Can you send your website link so I could check?

**Comment by zergaocean** [comment]
www.nouns-lads.com

**Comment by theshadowagent** [comment]
You or your dev added embed code literally inside the `div` with ID `mint-button`. Closing this since this should be an easy fix!

**Comment by zergaocean** [comment]
Thanks!
