### ISSUE TITLE
Issues with mobile mints

### ISSUE THREAD

**Issue by zergaocean** [buildship-dev/webflow-nft-components#9]
Some users have told us that they were not able to mine via mobile.

Either this page came up (see attachment), or the users were redirected to metamask, but then only a white blank page opened on metamask, without any request to mine. 

I would appreciate any response. 

![image](https://user-images.githubusercontent.com/97199109/149417906-4a2db291-b047-4f75-9b83-310c61570136.png)

**Comment by caffeinum** [comment]
#28 might be connected, this one lacks details, so closing for now
